### ISSUE TITLE
No download

### ISSUE THREAD

**Issue by bonniecobb** [rgarcia/shutterfly-address-book-exporter#1]
When I click the export button, the page reloads but there is no download. I am using the most up to date version of Chrome. Version 120.0.6099.129

**Comment by rgarcia** [comment]
just pushed a fix for this, will let you know when the chrome store approves and publishes it

**Comment by rgarcia** [comment]
the fix has been published, feel free to update and let me know if it works: https://chromewebstore.google.com/detail/shutterfly-address-book-e/lddlpciejomhjehckimopnomegilaocb

**Comment by bonniecobb** [comment]
It worked! Wow, thank you for making this. I'm so sick of Shutterfly holding my address book hostage. I'm so glad I found your solution. I hope you keep up with it so that when I inevitably need it again, its still around! Thank you!

**Comment by rgarcia** [comment]
Great to hear! Thanks for the review :)
