### ISSUE TITLE
Exported to where?

### ISSUE THREAD

**Issue by MarionGreene** [rgarcia/shutterfly-address-book-exporter#2]
Thank you so much for developing this add-on for those of us feeling hostage to Shutterfly. I followed the instructions, all seemed to go well, but I cannot for the life of me find on my computer where the file downloaded. Thank you for your help.

**Comment by rgarcia** [comment]
Hello! It should be wherever your browser is configured to download files. If you're in chrome, you can navigate to [chrome://downloads/](chrome://downloads/). Also, make sure you have the latest version of the extension installed. Go to [chrome://extensions/](chrome://extensions/) and make sure it says "1.1" next to the name of the extension.

**Comment by MarionGreene** [comment]
Thanks for the response. I do have v. 1.1. My Chrome is configured to download to "Downloads" (original!) but unfortunately the file isn't appearing there. I also checked "chrome://downloads/" and files downloaded before and since are there, but not this one. 

Is it possible my work has a security configuration that prevents the download (or otherwise jacks it up)? I know they don't like that when employees use Chrome at all, and in the past I've had to reload it. 
Thank you for your counsel - so appreciated!

**Comment by MarionGreene** [comment]
Stop the presses! I just closed and reloaded Shutterfly, and it worked. Sorry about that - and thank you for efforts to troubleshoot. Many thanks for your community contributions! And wishing you a wonderful 2024!

**Comment by MarionGreene** [comment]
And Happy 2024!

**Comment by rgarcia** [comment]
Great! Glad it worked. Happy new year!
