### ISSUE TITLE
Can't get Shutterfly Contact List Export extension to work.

### ISSUE THREAD

**Issue by k9logic** [rgarcia/shutterfly-address-book-exporter#3]
I can't seem to get an EXPORT option.  Loaded the extension, reloaded all pages, reloaded Chrome, and then restarted the PC.  Still no obvious EXPORT option.  I think I have granted all necessary permissions.  ??

**Comment by ldeits** [comment]
I am having the same issue as k9logic. I am also unable to have the export option. Thank you!

**Comment by rgarcia** [comment]
hey @k9logic and @ldeits! sorry about that... I just fixed this and submitted the update to the webstore: https://github.com/rgarcia/shutterfly-address-book-exporter/commit/f35813daed9b9545754815765f0c9814aeac61c6

Might take a few days for the update to get approved but in the meantime you could try pulling down this repository and building / running it.
